"""fix_metadata_column_name

Revision ID: 41033c35a1e0
Revises: 001
Create Date: 2025-09-26 09:21:28.170340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41033c35a1e0'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ids', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('ids_dl_code_key', 'ids', type_='unique')
    op.drop_index('idx_ids_dl_code', table_name='ids')
    op.create_index(op.f('ix_ids_dl_code'), 'ids', ['dl_code'], unique=True)
    op.drop_column('ids', 'metadata')
    op.drop_index('idx_logs_created_at', table_name='logs')
    op.drop_index('idx_logs_police_user_id', table_name='logs')
    op.drop_index('idx_logs_verification_result', table_name='logs')
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('idx_logs_verification_result', 'logs', ['verification_result'], unique=False)
    op.create_index('idx_logs_police_user_id', 'logs', ['police_user_id'], unique=False)
    op.create_index('idx_logs_created_at', 'logs', ['created_at'], unique=False)
    op.add_column('ids', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ids_dl_code'), table_name='ids')
    op.create_index('idx_ids_dl_code', 'ids', ['dl_code'], unique=False)
    op.create_unique_constraint('ids_dl_code_key', 'ids', ['dl_code'])
    op.drop_column('ids', 'meta_data')
    # ### end Alembic commands ###
